/*
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.unb.grupo10.oberon.ide;


/**
 * Use this class to register ide components.
 */
public class OberonIdeModule extends AbstractOberonIdeModule {
}
