/*
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.unb.grupo10.oberon.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.unb.grupo10.oberon.OberonRuntimeModule;
import org.unb.grupo10.oberon.OberonStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class OberonIdeSetup extends OberonStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new OberonRuntimeModule(), new OberonIdeModule()));
	}
	
}
