/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.unb.grupo10.oberon.oberon;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Boolean</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.unb.grupo10.oberon.oberon.OberonPackage#getBoolean()
 * @model
 * @generated
 */
public interface Boolean extends OberonType
{
} // Boolean
