/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.unb.grupo10.oberon.oberon;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declararion</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.unb.grupo10.oberon.oberon.Declararion#getTypes <em>Types</em>}</li>
 *   <li>{@link org.unb.grupo10.oberon.oberon.Declararion#getConsts <em>Consts</em>}</li>
 *   <li>{@link org.unb.grupo10.oberon.oberon.Declararion#getVars <em>Vars</em>}</li>
 *   <li>{@link org.unb.grupo10.oberon.oberon.Declararion#getProc <em>Proc</em>}</li>
 * </ul>
 *
 * @see org.unb.grupo10.oberon.oberon.OberonPackage#getDeclararion()
 * @model
 * @generated
 */
public interface Declararion extends Declarations
{
  /**
   * Returns the value of the '<em><b>Types</b></em>' containment reference list.
   * The list contents are of type {@link org.unb.grupo10.oberon.oberon.UserTypeDeclaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Types</em>' containment reference list.
   * @see org.unb.grupo10.oberon.oberon.OberonPackage#getDeclararion_Types()
   * @model containment="true"
   * @generated
   */
  EList<UserTypeDeclaration> getTypes();

  /**
   * Returns the value of the '<em><b>Consts</b></em>' containment reference list.
   * The list contents are of type {@link org.unb.grupo10.oberon.oberon.Constant}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Consts</em>' containment reference list.
   * @see org.unb.grupo10.oberon.oberon.OberonPackage#getDeclararion_Consts()
   * @model containment="true"
   * @generated
   */
  EList<Constant> getConsts();

  /**
   * Returns the value of the '<em><b>Vars</b></em>' containment reference list.
   * The list contents are of type {@link org.unb.grupo10.oberon.oberon.VarDeclaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vars</em>' containment reference list.
   * @see org.unb.grupo10.oberon.oberon.OberonPackage#getDeclararion_Vars()
   * @model containment="true"
   * @generated
   */
  EList<VarDeclaration> getVars();

  /**
   * Returns the value of the '<em><b>Proc</b></em>' containment reference list.
   * The list contents are of type {@link org.unb.grupo10.oberon.oberon.Procedure}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Proc</em>' containment reference list.
   * @see org.unb.grupo10.oberon.oberon.OberonPackage#getDeclararion_Proc()
   * @model containment="true"
   * @generated
   */
  EList<Procedure> getProc();

} // Declararion
