/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.unb.grupo10.oberon.oberon;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declarations</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.unb.grupo10.oberon.oberon.OberonPackage#getDeclarations()
 * @model
 * @generated
 */
public interface Declarations extends EObject
{
} // Declarations
