/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.unb.grupo10.oberon.oberon;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Designator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.unb.grupo10.oberon.oberon.Designator#getDesignator <em>Designator</em>}</li>
 *   <li>{@link org.unb.grupo10.oberon.oberon.Designator#getIndexes <em>Indexes</em>}</li>
 *   <li>{@link org.unb.grupo10.oberon.oberon.Designator#getAtribs <em>Atribs</em>}</li>
 *   <li>{@link org.unb.grupo10.oberon.oberon.Designator#getName <em>Name</em>}</li>
 *   <li>{@link org.unb.grupo10.oberon.oberon.Designator#getArgs <em>Args</em>}</li>
 * </ul>
 *
 * @see org.unb.grupo10.oberon.oberon.OberonPackage#getDesignator()
 * @model
 * @generated
 */
public interface Designator extends EObject
{
  /**
   * Returns the value of the '<em><b>Designator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Designator</em>' containment reference.
   * @see #setDesignator(Designator)
   * @see org.unb.grupo10.oberon.oberon.OberonPackage#getDesignator_Designator()
   * @model containment="true"
   * @generated
   */
  Designator getDesignator();

  /**
   * Sets the value of the '{@link org.unb.grupo10.oberon.oberon.Designator#getDesignator <em>Designator</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Designator</em>' containment reference.
   * @see #getDesignator()
   * @generated
   */
  void setDesignator(Designator value);

  /**
   * Returns the value of the '<em><b>Indexes</b></em>' containment reference list.
   * The list contents are of type {@link org.unb.grupo10.oberon.oberon.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Indexes</em>' containment reference list.
   * @see org.unb.grupo10.oberon.oberon.OberonPackage#getDesignator_Indexes()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getIndexes();

  /**
   * Returns the value of the '<em><b>Atribs</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Atribs</em>' attribute list.
   * @see org.unb.grupo10.oberon.oberon.OberonPackage#getDesignator_Atribs()
   * @model unique="false"
   * @generated
   */
  EList<String> getAtribs();

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.unb.grupo10.oberon.oberon.OberonPackage#getDesignator_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.unb.grupo10.oberon.oberon.Designator#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Args</b></em>' containment reference list.
   * The list contents are of type {@link org.unb.grupo10.oberon.oberon.Arguments}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' containment reference list.
   * @see org.unb.grupo10.oberon.oberon.OberonPackage#getDesignator_Args()
   * @model containment="true"
   * @generated
   */
  EList<Arguments> getArgs();

} // Designator
