/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.unb.grupo10.oberon.oberon;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Var Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.unb.grupo10.oberon.oberon.VarDeclaration#getVars <em>Vars</em>}</li>
 *   <li>{@link org.unb.grupo10.oberon.oberon.VarDeclaration#getVarType <em>Var Type</em>}</li>
 * </ul>
 *
 * @see org.unb.grupo10.oberon.oberon.OberonPackage#getVarDeclaration()
 * @model
 * @generated
 */
public interface VarDeclaration extends EObject
{
  /**
   * Returns the value of the '<em><b>Vars</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vars</em>' attribute list.
   * @see org.unb.grupo10.oberon.oberon.OberonPackage#getVarDeclaration_Vars()
   * @model unique="false"
   * @generated
   */
  EList<String> getVars();

  /**
   * Returns the value of the '<em><b>Var Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Type</em>' containment reference.
   * @see #setVarType(OberonType)
   * @see org.unb.grupo10.oberon.oberon.OberonPackage#getVarDeclaration_VarType()
   * @model containment="true"
   * @generated
   */
  OberonType getVarType();

  /**
   * Sets the value of the '{@link org.unb.grupo10.oberon.oberon.VarDeclaration#getVarType <em>Var Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var Type</em>' containment reference.
   * @see #getVarType()
   * @generated
   */
  void setVarType(OberonType value);

} // VarDeclaration
