/*
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.unb.grupo10.oberon;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class OberonStandaloneSetup extends OberonStandaloneSetupGenerated {

	public static void doSetup() {
		new OberonStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
