/*
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.unb.grupo10.oberon.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.unb.grupo10.oberon.ui.internal.OberonActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class OberonExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(OberonActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		OberonActivator activator = OberonActivator.getInstance();
		return activator != null ? activator.getInjector(OberonActivator.ORG_UNB_GRUPO10_OBERON_OBERON) : null;
	}

}
